#!/bin/bash
#PBS -N DeepLabV3_Validation
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -l mem=8g
#PBS -l walltime=00:15:00
#PBS -m abe

module purge
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1
module load torchvision/0.16.0-foss-2023a-CUDA-12.1.1
module load pyannote.audio/3.3.2-foss-2023a-CUDA-12.1.1

python3 /kyukon/data/gent/vo/000/gvo00058/vsc47066/IGIS_training/Scripts/validateMetrics.py IGIS_test trained_model_checkpoints/checkpoint_epoch_50.pth
